sampling:
  dim: 1
  method: uniform
  mu: 70
  num: 5000
  x_max: 1
  x_min: -1
training:
  activation: phi
  batchsize: 5000
  ifrandomsample: 'True'
  kernel_initializer: Glorot-normal
  lr: 0.001
  model: mscalenn2-multi-alphai-ci
  n_epoch: 100
  optim: Adam
  sub_layer_sizes:
  - 1
  - 150
  - 150
  - 150
  - 1
  sub_omegas:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
sampling:
  dim: 1
  method: uniform
  mu: 70
  num: 5000
  x_max: 1
  x_min: -1
training:
  activation: phi
  batchsize: 5000
  ifrandomsample: 'True'
  kernel_initializer: Glorot-normal
  lr: 0.001
  model: mscalenn2-multi-alphai-ci
  n_epoch: 100
  optim: Adam
  sub_layer_sizes:
  - 1
  - 150
  - 150
  - 150
  - 1
  sub_omegas:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
sampling:
  dim: 1
  method: uniform
  mu: 70
  num: 5000
  x_max: 1
  x_min: -1
training:
  activation: phi
  batchsize: 5000
  ifrandomsample: 'True'
  kernel_initializer: Glorot-normal
  lr: 0.001
  model: mscalenn2-multi-alphai-ci
  n_epoch: 100
  optim: Adam
  sub_layer_sizes:
  - 1
  - 150
  - 150
  - 150
  - 1
  sub_omegas:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
