SET:
- Batch_size: 1
  Boundary_points: 2500
  Section: 0,1000,4500
  Domain_points: 6400
  Epoch: 10000
  Fig_Record_Interve: 100
  Record_Interve: 10
  Learn_scale: false
  Model: mscalenn2
  PDE_Solver: src_PDE/Poisson.py
  Penalty_boundary: 1000
  Penalty_data: 0
  Penalty_pde: 1
  Seed: 42
  Save_Path: Result/Poisson/expr_3_11_p_p_mu_1_sub_25_msdnn/
  Scale_Coeff: 1,11,21,31,41,51,61,71,81,91,101,111,121,131,141,151,161,171,181,191,201,211,221,231,241
  Src_agent: src_lam/Agent.py
  Sub_number: 25
  Test_points: 6400
  lr: 0.001
  mu: 1
  shape: poly_with_hole
  Task: deepxde #deepxde
  Note: This is to test mscalednn in contribution of each scale
  MOE: false
  sp_k: 25
Subnet:
- Act_Set: phi,phi,phi
  Ini_Set: xavier_uniform
  Layer_Set: 2,59,59,59,1
  Residual: false
